development:
  adapter: postgresql
  encoding: unicode
  database: st-pag-dev
  pool: 5
  username: manstike
  password: 1234
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: st-pag-test

  pool: 5
  username: manstike
  password: 1234
  host: localhost

